# Generated by Django 5.1.7 on 2025-03-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_coins_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
