# Generated by Django 5.1.7 on 2025-03-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coins',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
