# Generated by Django 5.1.7 on 2025-03-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_itemcompra_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcompra',
            name='image',
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
    ]
